spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/db_futbol?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka